server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/clarence-wzy/springcloud-demo.git
          username: 1093944886@qq.com
          password: wojiaowuziyi*1
          search-paths: config
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/